spring.application.name=chatbot-atendimento-ia
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-lite-latest:generateContent
# Credenciais da Meta (Cole seus dados reais aqui)
# Credenciais da Meta
meta.api.token=${META_API_TOKEN}
meta.phone.id=${META_PHONE_ID}
